cc_library(
    name = "math",
    srcs = [
        "src/algebra.cpp",
        "src/numerical_utilities.cpp"
    ],
    hdrs = [
        "hdr/algebra.h",
        "hdr/mathematical_analysis.h",
        "hdr/numerical_utilities.h"
    ],
    visibility = ["//visibility:public"]
)