load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "test_numerical_utilities",
    srcs = ["test_numerical_utilities.cpp"],
    deps = [
        "//engine/math",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "test_algebra",
    srcs = ["test_algebra.cpp"],
    deps = [
        "//engine/math",
        "@com_google_googletest//:gtest_main",
    ],
)