cc_library(
    name = "collision",
    srcs = [
        "src/collision_model.cpp",
        "src/area_description.cpp"
    ],
    hdrs = [
        "hdr/area_description.h",
        "hdr/collision_model.h"
    ],
    deps = [
        "//engine/math"
    ],
    visibility = ["//visibility:public"]
)