cc_library(
    name = "movement_handler",
    srcs = ["src/movement_handler.cpp"],
    hdrs = ["hdr/movement_handler.h"],
    deps = [
        "//engine/math",
        "//engine/physics/collision_model:collision",
    ],
    visibility = ["//visibility:public"]
)