cc_library(
    name = "window_manager",
    hdrs = ["hdr/window_manager.h"],
    visibility = ["//visibility:public"]
)

cc_library(
    name = "side_bar",
    hdrs = ["hdr/side_bar.h"],
    srcs = ["src/side_bar.cpp"],
    deps = ["//engine/physics/collision_model:collision"],
    visibility = ["//visibility:public"],
)