cc_library(
    name = "lidar",
    srcs = ["src/lidar.cpp"],
    hdrs = ["hdr/lidar.h"],
    deps = [
        "//engine/physics/collision_model:collision",
        "//engine/math"
    ],
    visibility = ["//visibility:public"]
)