cc_library(
    name = "car_model",
    srcs = ["src/car_model.cpp"],
    hdrs = ["hdr/car_model.h"],
    deps = [
        "//engine/physical_objects/physical_model",
        "//engine/physics/movement_handler",
        "//engine/physics/constants"
    ],
    visibility = ["//visibility:public"]
)